// Generated by Calepin. Do not edit.

#import "/_calepin/calepin.typ" as runtime
#import "runtime-config.typ": config

#let _bound = runtime.bind(config)
#let pages = _bound.pages
#let setup = _bound.setup
#let chunk = _bound.chunk
#let inline = _bound.inline
#let results = _bound.results
#let chunk_from_raw_plain = _bound.chunk_from_raw_plain
#let code-block = _bound.code-block
#let elements = _bound.elements
#let _resolve-asset-href = _bound._resolve-asset-href
#let _resolve-asset-path = _bound._resolve-asset-path
#let document = _bound.document
