// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "presenting",
  source: "presenting/notes.typ",
  "raw-langs": ("bash", "d2", "dot", "mermaid", "python", "r", "tikz"),
)
