// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "incremental",
  source: "incremental/steps.typ",
  "raw-langs": ("d2", "dot", "mermaid", "python", "r", "tikz"),
)
